--
-- AUTHOR: ARMANDO VALDERRAMA NAVARRO
--

--
-- CREACION DE LA BASE DE DATOS
-- 

CREATE DATABASE banco;

--
-- DLL DE LA BASE DE DATOS
--

CREATE TABLE CLIENTE(
    CLIENTE_ID NUMERIC(5,0) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO_PATERNO VARCHAR(50) NOT NULL,
    APELLIDO_MATERNO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    CONTRASENA VARCHAR(200) NOT NULL,

    CONSTRAINT CLIENTE_PK PRIMARY KEY (CLIENTE_ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_CUENTA;

CREATE TABLE CUENTA(
    CUENTA_ID NUMERIC(5,0) NOT NULL DEFAULT NEXTVAL('SEQ_CUENTA'),
    NUMERO_CUENTA NUMERIC(15,0) NOT NULL,
    SALDO NUMERIC(20,3) NOT NULL,
    CLIENTE_ID NUMERIC(5,0) NOT NULL,

    CONSTRAINT CUENTA_PK PRIMARY KEY (CUENTA_ID)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_TRANSACCION;

CREATE TABLE TRANSACCION(
    TRANSACCION_ID NUMERIC(5,0) NOT NULL DEFAULT NEXTVAL('SEQ_TRANSACCION'),
    CUENTA_ID_ORIGEN NUMERIC(5,0) NOT NULL,
    CUENTA_ID_DESTINO NUMERIC(5,0) NULL,

    CONSTRAINT TRANSACCION_PK PRIMARY KEY (TRANSACCION_ID)
);

CREATE TABLE TIPO_TRANSACCION(
    TIPO_TRANSACCION_ID NUMERIC(5,0) NOT NULL,
    TIPO_TRANSACCION VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,

    CONSTRAINT TIPO_TRANSACCION_PK PRIMARY KEY (TIPO_TRANSACCION_ID)
);

ALTER TABLE CUENTA
    ADD CONSTRAINT cuenta_cliente FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID);

ALTER TABLE TRANSACCION
    ADD CONSTRAINT cuenta_origen FOREIGN KEY (CUENTA_ID_ORIGEN) REFERENCES CUENTA (CUENTA_ID);

ALTER TABLE TRANSACCION
    ADD CONSTRAINT cuenta_destino FOREIGN KEY (CUENTA_ID_DESTINO) REFERENCES CUENTA (CUENTA_ID);

--
-- DML DE LA BASE DE DATOS
--

INSERT INTO CLIENTE (CLIENTE_ID, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, CORREO, CONTRASENA) VALUES (1, 'Armando', 'Valderrama', 'Navarro', 'armandovn@gmail.com', '12345');

INSERT INTO CUENTA (NUMERO_CUENTA, SALDO, CLIENTE_ID) VALUES (313156353, 1000000.000, 1);

INSERT INTO TIPO_TRANSACCION (TIPO_TRANSACCION_ID, TIPO_TRANSACCION, DESCRIPCION) VALUES (1, 'DEPOSITO', 'DEPOSITO A SU CUENTA BANCARIA');